[package]
authors = ["Marcel Märtens <marcel.cochem@googlemail.com>"]
edition = "2018"
name = "veloren_common_sys"
version = "0.8.0"

[lib]
name = "common_sys"

[features]
tracy = ["tracy-client"]
simd = ["vek/platform_intrinsics"]

default = ["simd"]

[dependencies]
common = {package = "veloren-common", path = "../../common"}

rand = "0.7"
rayon = "1.3.0"
tracing = { version = "0.1", default-features = false }
vek = { version = "0.12.0", features = ["serde"] }

# ECS
specs = { git = "https://github.com/amethyst/specs.git", features = ["serde", "storage-event-control"], rev = "7a2e348ab2223818bad487695c66c43db88050a5" }

# Serde
serde = { version = "1.0.110", features = ["derive"] }

# Tracy
tracy-client = { version = "0.9.0", optional = true }
