[package]
authors = ["Ben Wallis <atomyc@gmail.com>"]
name = "veloren-voxygen-egui"
edition = "2018"
version = "0.9.0"

[features]
use-dyn-lib = ["lazy_static", "voxygen-dynlib"]
be-dyn-lib = []

[dependencies]
client = {package = "veloren-client", path = "../../client"}
common = {package = "veloren-common", path = "../../common"}
egui = "0.13"
egui_winit_platform = "0.9"
voxygen-dynlib = {package = "veloren-voxygen-dynlib", path = "../dynlib", optional = true}

# Hot Reloading
lazy_static = {version = "1.4.0", optional = true}

