[package]
authors = ["juliancoffee <lightdarkdaughter@gmail.com>"]
edition = "2018"
name = "veloren-i18n-check"
description = "crate to analyze localization assets to find what needs update"
version = "0.9.0"

[[bin]]
name = "i18n-check"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
ron = "0.6"
git2 = "0.13"
