name: Mirror Gitlab repo

# Every hour
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  mirror-gitlab-repo:
    runs-on: ubuntu-20.04

    steps:
      - name: Install git-filter-repo
        run: git clone https://github.com/newren/git-filter-repo.git;
          ./git-filter-repo/git-filter-repo --help

      - name: Clone Gitlab repo
        run: git lfs install;
          git clone https://gitlab.com/veloren/veloren.git;

      - name: Uninstall LFS
        run: cd veloren;
          git lfs uninstall;
          git lfs migrate export --include="*" --everything;

      - name: Remove workflow files
        run: cd veloren;
          ../git-filter-repo/git-filter-repo --invert-paths --path .github --force;

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          tags: true
          directory: veloren