# cargo clippy is a superset of cargo check, so we don't check manually
code-quality:
  extends: .recompile-branch
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  tags: ["xvartest"]
  script:
    - ln -s /dockercache/target target
    - cat ./.gitlab/scripts/code-quality.sh
    - source ./.gitlab/scripts/code-quality.sh

security:
  extends: .recompile-branch
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  tags: ["xvartest"]
  allow_failure: true
  script:
    - ln -s /dockercache/target target
    - cat ./.gitlab/scripts/security.sh
    - source ./.gitlab/scripts/security.sh
