# cargo clippy is a superset of cargo check, so we don't check manually
code-quality:
  extends: .recompile-branch
  stage: check
  script:
    - ln -s /dockercache/cache-all target
    - rm -r target/debug/incremental/veloren_* || echo "all good" # TMP FIX FOR 2021-03-22-nightly
    - cargo clippy --all-targets --locked -- -D warnings
    - cargo fmt --all -- --check

tag-test:
  extends: .recompile-branch
  stage: check
  script:
    - git config --global user.email "gitlab@veloren.net"
    - git config --global user.name "Veloren Admin"
    - git remote remove api-origin || echo "api-origin remote did not already exist"
    - git remote add api-origin https://oauth2:$TAGTOKEN@gitlab.com/veloren/veloren.git
    - git tag -f airshipper
    - git push api-origin --tags -f

security:
  extends: .recompile-branch
  stage: check
  allow_failure: true
  script:
    - ln -s /dockercache/cache-all target
    - cargo audit
