check:
  extends: .recompile-branch
  stage: check
  script:
    - ln -s /dockercache/cache-all target
    - cargo check --locked
    - cargo check --examples --locked

code-quality:
  extends: .recompile-branch
  stage: check
  script:
    - ln -s /dockercache/cache-all target
    - cargo clippy -- -D warnings
    - cargo clippy --tests -- -D warnings
    - cargo fmt --all -- --check

security:
  extends: .recompile-branch
  stage: check
  allow_failure: true
  script:
    - ln -s /dockercache/cache-all target
    - cargo audit
