# cargo clippy is a superset of cargo check, so we don't check manually
code-quality:
  extends: .recompile-branch
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  script:
    - ln -s /dockercache/target target
    - rm -r target/debug/incremental/* || echo "all good" # TMP FIX FOR 2021-03-22-nightly
    - cargo clippy --all-targets --locked --features="bin_csv,bin_graphviz,bin_bot,asset_tweak" -- -D warnings
    # Ensure that the veloren-voxygen default-publish feature builds as it excludes some default features
    - cargo clippy -p veloren-voxygen --locked --no-default-features --features="default-publish" -- -D warnings
    - cargo fmt --all -- --check

security:
  extends: .recompile-branch
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  allow_failure: true
  script:
    - ln -s /dockercache/target target
    - cargo audit
