check:
  extends: .recompile-branch
  stage: check
  script:
    - ln -s /dockercache/cache-all target
    - cargo fmt --all -- --check
    # TODO: currently there are some examples that fail clippy
    # - cargo clippy --all-targets --locked -- -D warnings
    - cargo clippy --bins --tests --locked -- -D warnings
    - cargo test
    - cargo test --package veloren-voxygen --lib test_all_localizations -- --nocapture --ignored

security:
  extends: .recompile-branch
  stage: check
  allow_failure: true
  script:
    - ln -s /dockercache/cache-all target
    - cargo audit
