# cargo clippy is a superset of cargo check, so we don't check manually
code-quality:
  extends: .recompile-branch
  stage: check
  script:
    - ln -s /dockercache/cache-all target
    - cargo clippy --tests --examples --benches --bins --locked -- -D warnings
    - cargo fmt --all -- --check

security:
  extends: .recompile-branch
  stage: check
  allow_failure: true
  script:
    - ln -s /dockercache/cache-all target
    - cargo audit
